apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: navidrome
      version: "6.7.6"
      sourceRef:
        kind: HelmRepository
        name: navidrome-repo
        namespace: default
  values:
    image:
      repository: deluan/navidrome
      tag: "0.58.5"
    
    service:
      main:
        type: NodePort
        ports:
          http:
            port: 4533
            targetPort: 4533
            nodePort: 30533
    
    env:
      ND_MUSICFOLDER: "C:\\Users\\ahorn\\Music"