apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: syncthing
      version: "12.0.0"
      sourceRef:
        kind: HelmRepository
        name: syncthing-repo
        namespace: default
  values:
    replicaCount: 1
    
    # Single replica - Syncthing is stateful and requires a single instance
    # to prevent conflicts when syncing files
    
    livenessProbe:
      httpGet:
        path: /
        port: 8384
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /
        port: 8384
      initialDelaySeconds: 5
      periodSeconds: 5
